### ISSUE TITLE
Install fails if you don't already have pyyaml in your virtualenv

### ISSUE THREAD

**Issue by offbyone** [Kraymer/flinck#12]
```
pip install -e git+https://github.com/Kraymer/flinck\#egg\=flinck
Already using interpreter /usr/local/opt/python/bin/python2.7
New python executable in /Users/offby1/.local/venvs/flinck/bin/python2.7
Also creating executable in /Users/offby1/.local/venvs/flinck/bin/python
Installing setuptools, pip, wheel...done.
Obtaining flinck from git+https://github.com/Kraymer/flinck#egg=flinck
  Cloning https://github.com/Kraymer/flinck to ./.local/venvs/flinck/src/flinck
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/offby1/.local/venvs/flinck/src/flinck/setup.py", line 11, in <module>
        from flinck import __version__
      File "flinck/__init__.py", line 12, in <module>
        from . import confit
      File "flinck/confit.py", line 24, in <module>
        import yaml
    ImportError: No module named yaml

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/offby1/.local/venvs/flinck/src/flinck/
Failed to pip install.  Aborting.
```

This is because in order to import the `__version__` you pull in `confit`, which requires `yaml`... but that's in your `install_requires`

So this'll work in dev virtualenvs, but not without prep. I think you'll need to find a way to get the version without the import.

**Comment by Kraymer** [comment]
Thanks for the report, I'll fix that tonight.

**Comment by Kraymer** [comment]
I wasn't able to reproduce the problem, please reopen it if my patch did not fix it.

**Comment by offbyone** [comment]
That resolves it nicely, thank you.
