### ISSUE TITLE
KeyError: u'rating'

### ISSUE THREAD

**Issue by onedr0p** [Kraymer/flinck#28]
```
WARNING: Found no folder defining a compatible range for '7.8'
WARNING: /wash/Movies/Top Rated/rating/Tangled (2010) [7.8] already exist
INFO: Tangled (2010).mkv: done
Traceback (most recent call last):
  File "/usr/bin/flinck", line 9, in <module>
    load_entry_point('flinck==0.3.1', 'console_scripts', 'flinck')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flinck/__init__.py", line 90, in flinck_cli
    linker.flink(item)
  File "/usr/lib/python2.7/site-packages/flinck/linker.py", line 96, in flink
    self.link_format), item)
  File "/usr/lib/python2.7/site-packages/flinck/linker.py", line 25, in resolve_template
    path = path.replace(p, item[p.strip('%{}')])
KeyError: u'rating'
```

**Comment by Kraymer** [comment]
Can you reproduce it ? (i can't)
What is the output with `-vv` flag ?

**Comment by onedr0p** [comment]
Here's output with the vv flag

```
WARNING: Found no folder defining a compatible range for '7.8'
WARNING: /wash/Movies/Top Rated/rating/Tangled (2010) [7.8] already exist
INFO: Tangled (2010).mkv: done
DEBUG: Query: {'year': '2000', 'tomatoes': False, 'fullplot': False, 'title': 'Heavy Metal'}
Traceback (most recent call last):
  File "/usr/bin/flinck", line 9, in <module>
    load_entry_point('flinck==0.3.1', 'console_scripts', 'flinck')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flinck/__init__.py", line 90, in flinck_cli
    linker.flink(item)
  File "/usr/lib/python2.7/site-packages/flinck/linker.py", line 96, in flink
    self.link_format), item)
  File "/usr/lib/python2.7/site-packages/flinck/linker.py", line 25, in resolve_template
    path = path.replace(p, item[p.strip('%{}')])
KeyError: u'rating'
```

**Comment by Kraymer** [comment]
v0.3.2 has just been shipped with the fix 🚈 💨
