### ISSUE TITLE
Which server is unavailable ?

### ISSUE THREAD

**Issue by Riduidel** [Kraymer/flinck#32]
I think that when some server is unavailable, flinck fails noisily (which is good). But which server failed ? The error message is hiding that detail :

	flinck Videos/dns323/films_parents/
	WARNING: Steven Spielberg - Indiana Jones et les aventuriers de l'arche perdue [DivX.Fr].avi: no result in Open Movie Database
	Traceback (most recent call last):
	  File "/usr/local/bin/flinck", line 9, in <module>
		load_entry_point('flinck==0.3.2', 'console_scripts', 'flinck')()
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
		return callback(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/flinck/__init__.py", line 87, in flinck_cli
		item = brain.search_filename(fpath, by)
	  File "/usr/local/lib/python2.7/dist-packages/flinck/brain.py", line 141, in search_filename
		item = search_by(title, year, fields)
	  File "/usr/local/lib/python2.7/dist-packages/flinck/brain.py", line 113, in search_by
		item = omdb.get(**query)
	  File "/usr/local/lib/python2.7/dist-packages/omdb/api.py", line 23, in get
		return _client.get(**params)
	  File "/usr/local/lib/python2.7/dist-packages/omdb/client.py", line 104, in get
		data = self.request(**params).json()
	  File "/usr/local/lib/python2.7/dist-packages/omdb/client.py", line 60, in request
		res.raise_for_status()
	  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 825, in raise_for_status
		raise HTTPError(http_error_msg, response=self)
	requests.exceptions.HTTPError: 503 Server Error: Service Unavailable

**Comment by Riduidel** [comment]
On a side note, I guess this is related to my Raspberry being unable to connect to Google Api ... but I access it through SSH from a distant site, so web connection work. And I have an API key in my config.yaml file (it was incorrectly written without "", but I fixed it)
